// const generalAvailability = {
//     maxCapacity: {},
// };


const getRoomsAvailability = () => {
    let totalRooms = {
        closeForSale: false,

        StandardRooms: {
            categoryCloseForSale: false,
            amount: 50,
            priceRates: {
                price: {
                    single: 0.9,
                    double: 1,
                    triple: 1.25,
                    tripleAdults: 1.3,
                    quad: 1.5,
                },
                baby: 40,
            },
            maxCapacity: [
                // [adults, kids, babies],
                {adults: 3, kids: 0, babies: 0},
                {adults: 2, kids: 2, babies: 0},
                {adults: 2, kids: 1, babies: 1},
                {adults: 2, kids: 0, babies: 2},
                {adults: 1, kids: 3, babies: 0},
                {adults: 1, kids: 2, babies: 1},
                {adults: 1, kids: 1, babies: 2},
                {adults: 1, kids: 0, babies: 2},
                {adults: 0, kids: 4, babies: 0},
            ],
        },
        ExecutiveRooms: {
            categoryCloseForSale: false,
            amount: 40,
            maxCapacity: [
                // [adults, kids, babies],
                {adults: 3, kids: 0, babies: 0},
                {adults: 2, kids: 1, babies: 0},
                {adults: 2, kids: 0, babies: 1},
                {adults: 1, kids: 2, babies: 0},
                {adults: 1, kids: 1, babies: 1},
                {adults: 1, kids: 0, babies: 2},
                {adults: 0, kids: 3, babies: 0},
            ],
        },
        Suits: {
            categoryCloseForSale: false,
            amount: 10,
            maxCapacity: [
                // [adults, kids, babies],
                {adults: 2, kids: 0, babies: 1},
                {adults: 1, kids: 1, babies: 1},
            ],
        },
    };

    return totalRooms;
};


const dayTemplate = () => {
    let day = {
        day: "",
        // numericalDay: 0,
        comment: "",
        note: "",

        priceStage: 5,

        roomsAvailable: getRoomsAvailability(),
        
    };

    return day;
};

const regularYearTemplate = (year) => {
    let yearKey = `year${year}`;

    let Availability = {
        [yearKey]: {
            year: year,

            seasons: {
                winter: {
                    january: {
                        first: dayTemplate(),
                        second: dayTemplate(),
                        third: dayTemplate(),
                        fourth: dayTemplate(),
                        fifth: dayTemplate(),
                        sixth: dayTemplate(),
                        seventh: dayTemplate(),
                        eighth: dayTemplate(),
                        ninth: dayTemplate(),
                        tenth: dayTemplate(),
                        eleventh: dayTemplate(),
                        twelfth: dayTemplate(),
                        thirteenth: dayTemplate(),
                        fourteenth: dayTemplate(),
                        fifteenth: dayTemplate(),
                        sixteenth: dayTemplate(),
                        seventeenth: dayTemplate(),
                        eighteenth: dayTemplate(),
                        nineteenth: dayTemplate(),
                        twentieth: dayTemplate(),
                        twentyFirst: dayTemplate(),
                        twentySecond: dayTemplate(),
                        twentyThird: dayTemplate(),
                        twentyFourth: dayTemplate(),
                        twentyFifth: dayTemplate(),
                        twentySixth: dayTemplate(),
                        twentySeventh: dayTemplate(),
                        twentyEighth: dayTemplate(),
                        twentyNinth: dayTemplate(),
                        thirtieth: dayTemplate(),
                        thirtyFirst: dayTemplate(),
                    },
                    february: {
                        first: {},
                        second: {},
                        third: {},
                        fourth: {},
                        fifth: {},
                        sixth: {},
                        seventh: {},
                        eighth: {},
                        ninth: {},
                        tenth: {},
                        eleventh: {},
                        twelfth: {},
                        thirteenth: {},
                        fourteenth: {},
                        fifteenth: {},
                        sixteenth: {},
                        seventeenth: {},
                        eighteenth: {},
                        nineteenth: {},
                        twentieth: {},
                        twentyFirst: {},
                        twentySecond: {},
                        twentyThird: {},
                        twentyFourth: {},
                        twentyFifth: {},
                        twentySixth: {},
                        twentySeventh: {},
                        twentyEighth: {},
                    },
                    march: {
                        first: {},
                        second: {},
                        third: {},
                        fourth: {},
                        fifth: {},
                        sixth: {},
                        seventh: {},
                        eighth: {},
                        ninth: {},
                        tenth: {},
                        eleventh: {},
                        twelfth: {},
                        thirteenth: {},
                        fourteenth: {},
                        fifteenth: {},
                        sixteenth: {},
                        seventeenth: {},
                        eighteenth: {},
                        nineteenth: {},
                        twentieth: {},
                        twentyFirst: {},
                        twentySecond: {},
                        twentyThird: {},
                        twentyFourth: {},
                        twentyFifth: {},
                        twentySixth: {},
                        twentySeventh: {},
                        twentyEighth: {},
                        twentyNinth: {},
                        thirtieth: {},
                        thirtyFirst: {},
                    },
                },
                spring: {
                    april: {
                        first: {},
                        second: {},
                        third: {},
                        fourth: {},
                        fifth: {},
                        sixth: {},
                        seventh: {},
                        eighth: {},
                        ninth: {},
                        tenth: {},
                        eleventh: {},
                        twelfth: {},
                        thirteenth: {},
                        fourteenth: {},
                        fifteenth: {},
                        sixteenth: {},
                        seventeenth: {},
                        eighteenth: {},
                        nineteenth: {},
                        twentieth: {},
                        twentyFirst: {},
                        twentySecond: {},
                        twentyThird: {},
                        twentyFourth: {},
                        twentyFifth: {},
                        twentySixth: {},
                        twentySeventh: {},
                        twentyEighth: {},
                        twentyNinth: {},
                        thirtieth: {},
                    },
                    may: {
                        first: {},
                        second: {},
                        third: {},
                        fourth: {},
                        fifth: {},
                        sixth: {},
                        seventh: {},
                        eighth: {},
                        ninth: {},
                        tenth: {},
                        eleventh: {},
                        twelfth: {},
                        thirteenth: {},
                        fourteenth: {},
                        fifteenth: {},
                        sixteenth: {},
                        seventeenth: {},
                        eighteenth: {},
                        nineteenth: {},
                        twentieth: {},
                        twentyFirst: {},
                        twentySecond: {},
                        twentyThird: {},
                        twentyFourth: {},
                        twentyFifth: {},
                        twentySixth: {},
                        twentySeventh: {},
                        twentyEighth: {},
                        twentyNinth: {},
                        thirtieth: {},
                        thirtyFirst: {},
                    },
                    june: {
                        first: {},
                        second: {},
                        third: {},
                        fourth: {},
                        fifth: {},
                        sixth: {},
                        seventh: {},
                        eighth: {},
                        ninth: {},
                        tenth: {},
                        eleventh: {},
                        twelfth: {},
                        thirteenth: {},
                        fourteenth: {},
                        fifteenth: {},
                        sixteenth: {},
                        seventeenth: {},
                        eighteenth: {},
                        nineteenth: {},
                        twentieth: {},
                        twentyFirst: {},
                        twentySecond: {},
                        twentyThird: {},
                        twentyFourth: {},
                        twentyFifth: {},
                        twentySixth: {},
                        twentySeventh: {},
                        twentyEighth: {},
                        twentyNinth: {},
                        thirtieth: {},
                    },
                },
                summer: {
                    july: {
                        first: {},
                        second: {},
                        third: {},
                        fourth: {},
                        fifth: {},
                        sixth: {},
                        seventh: {},
                        eighth: {},
                        ninth: {},
                        tenth: {},
                        eleventh: {},
                        twelfth: {},
                        thirteenth: {},
                        fourteenth: {},
                        fifteenth: {},
                        sixteenth: {},
                        seventeenth: {},
                        eighteenth: {},
                        nineteenth: {},
                        twentieth: {},
                        twentyFirst: {},
                        twentySecond: {},
                        twentyThird: {},
                        twentyFourth: {},
                        twentyFifth: {},
                        twentySixth: {},
                        twentySeventh: {},
                        twentyEighth: {},
                        twentyNinth: {},
                        thirtieth: {},
                        thirtyFirst: {},
                    },
                    august: {
                        first: {},
                        second: {},
                        third: {},
                        fourth: {},
                        fifth: {},
                        sixth: {},
                        seventh: {},
                        eighth: {},
                        ninth: {},
                        tenth: {},
                        eleventh: {},
                        twelfth: {},
                        thirteenth: {},
                        fourteenth: {},
                        fifteenth: {},
                        sixteenth: {},
                        seventeenth: {},
                        eighteenth: {},
                        nineteenth: {},
                        twentieth: {},
                        twentyFirst: {},
                        twentySecond: {},
                        twentyThird: {},
                        twentyFourth: {},
                        twentyFifth: {},
                        twentySixth: {},
                        twentySeventh: {},
                        twentyEighth: {},
                        twentyNinth: {},
                        thirtieth: {},
                        thirtyFirst: {},
                    },
                    september: {
                        first: {},
                        second: {},
                        third: {},
                        fourth: {},
                        fifth: {},
                        sixth: {},
                        seventh: {},
                        eighth: {},
                        ninth: {},
                        tenth: {},
                        eleventh: {},
                        twelfth: {},
                        thirteenth: {},
                        fourteenth: {},
                        fifteenth: {},
                        sixteenth: {},
                        seventeenth: {},
                        eighteenth: {},
                        nineteenth: {},
                        twentieth: {},
                        twentyFirst: {},
                        twentySecond: {},
                        twentyThird: {},
                        twentyFourth: {},
                        twentyFifth: {},
                        twentySixth: {},
                        twentySeventh: {},
                        twentyEighth: {},
                        twentyNinth: {},
                        thirtieth: {},
                    },
                },
                autumn: {
                    october: {
                        first: {},
                        second: {},
                        third: {},
                        fourth: {},
                        fifth: {},
                        sixth: {},
                        seventh: {},
                        eighth: {},
                        ninth: {},
                        tenth: {},
                        eleventh: {},
                        twelfth: {},
                        thirteenth: {},
                        fourteenth: {},
                        fifteenth: {},
                        sixteenth: {},
                        seventeenth: {},
                        eighteenth: {},
                        nineteenth: {},
                        twentieth: {},
                        twentyFirst: {},
                        twentySecond: {},
                        twentyThird: {},
                        twentyFourth: {},
                        twentyFifth: {},
                        twentySixth: {},
                        twentySeventh: {},
                        twentyEighth: {},
                        twentyNinth: {},
                        thirtieth: {},
                        thirtyFirst: {},
                    },
                    november: {
                        first: {},
                        second: {},
                        third: {},
                        fourth: {},
                        fifth: {},
                        sixth: {},
                        seventh: {},
                        eighth: {},
                        ninth: {},
                        tenth: {},
                        eleventh: {},
                        twelfth: {},
                        thirteenth: {},
                        fourteenth: {},
                        fifteenth: {},
                        sixteenth: {},
                        seventeenth: {},
                        eighteenth: {},
                        nineteenth: {},
                        twentieth: {},
                        twentyFirst: {},
                        twentySecond: {},
                        twentyThird: {},
                        twentyFourth: {},
                        twentyFifth: {},
                        twentySixth: {},
                        twentySeventh: {},
                        twentyEighth: {},
                        twentyNinth: {},
                        thirtieth: {},
                    },
                    december: {
                        first: {},
                        second: {},
                        third: {},
                        fourth: {},
                        fifth: {},
                        sixth: {},
                        seventh: {},
                        eighth: {},
                        ninth: {},
                        tenth: {},
                        eleventh: {},
                        twelfth: {},
                        thirteenth: {},
                        fourteenth: {},
                        fifteenth: {},
                        sixteenth: {},
                        seventeenth: {},
                        eighteenth: {},
                        nineteenth: {},
                        twentieth: {},
                        twentyFirst: {},
                        twentySecond: {},
                        twentyThird: {},
                        twentyFourth: {},
                        twentyFifth: {},
                        twentySixth: {},
                        twentySeventh: {},
                        twentyEighth: {},
                        twentyNinth: {},
                        thirtieth: {},
                        thirtyFirst: {},
                    },
                },
            },
        }
    };

    return Availability;
};


const skipYearTemplate = (year) => {
    let yearKey = `year${year}`;

    let Availability = {
        [yearKey]: {
            year: year,

            seasons: {
                winter: {
                    january: {
                        first: {},
                        second: {},
                        third: {},
                        fourth: {},
                        fifth: {},
                        sixth: {},
                        seventh: {},
                        eighth: {},
                        ninth: {},
                        tenth: {},
                        eleventh: {},
                        twelfth: {},
                        thirteenth: {},
                        fourteenth: {},
                        fifteenth: {},
                        sixteenth: {},
                        seventeenth: {},
                        eighteenth: {},
                        nineteenth: {},
                        twentieth: {},
                        twentyFirst: {},
                        twentySecond: {},
                        twentyThird: {},
                        twentyFourth: {},
                        twentyFifth: {},
                        twentySixth: {},
                        twentySeventh: {},
                        twentyEighth: {},
                        twentyNinth: {},
                        thirtieth: {},
                        thirtyFirst: {},
                    },
                    february: {
                        first: {},
                        second: {},
                        third: {},
                        fourth: {},
                        fifth: {},
                        sixth: {},
                        seventh: {},
                        eighth: {},
                        ninth: {},
                        tenth: {},
                        eleventh: {},
                        twelfth: {},
                        thirteenth: {},
                        fourteenth: {},
                        fifteenth: {},
                        sixteenth: {},
                        seventeenth: {},
                        eighteenth: {},
                        nineteenth: {},
                        twentieth: {},
                        twentyFirst: {},
                        twentySecond: {},
                        twentyThird: {},
                        twentyFourth: {},
                        twentyFifth: {},
                        twentySixth: {},
                        twentySeventh: {},
                        twentyEighth: {},
                        twentyNinth: {},
                    },
                    march: {
                        first: {},
                        second: {},
                        third: {},
                        fourth: {},
                        fifth: {},
                        sixth: {},
                        seventh: {},
                        eighth: {},
                        ninth: {},
                        tenth: {},
                        eleventh: {},
                        twelfth: {},
                        thirteenth: {},
                        fourteenth: {},
                        fifteenth: {},
                        sixteenth: {},
                        seventeenth: {},
                        eighteenth: {},
                        nineteenth: {},
                        twentieth: {},
                        twentyFirst: {},
                        twentySecond: {},
                        twentyThird: {},
                        twentyFourth: {},
                        twentyFifth: {},
                        twentySixth: {},
                        twentySeventh: {},
                        twentyEighth: {},
                        twentyNinth: {},
                        thirtieth: {},
                        thirtyFirst: {},
                    },
                },
                spring: {
                    april: {
                        first: {},
                        second: {},
                        third: {},
                        fourth: {},
                        fifth: {},
                        sixth: {},
                        seventh: {},
                        eighth: {},
                        ninth: {},
                        tenth: {},
                        eleventh: {},
                        twelfth: {},
                        thirteenth: {},
                        fourteenth: {},
                        fifteenth: {},
                        sixteenth: {},
                        seventeenth: {},
                        eighteenth: {},
                        nineteenth: {},
                        twentieth: {},
                        twentyFirst: {},
                        twentySecond: {},
                        twentyThird: {},
                        twentyFourth: {},
                        twentyFifth: {},
                        twentySixth: {},
                        twentySeventh: {},
                        twentyEighth: {},
                        twentyNinth: {},
                        thirtieth: {},
                    },
                    may: {
                        first: {},
                        second: {},
                        third: {},
                        fourth: {},
                        fifth: {},
                        sixth: {},
                        seventh: {},
                        eighth: {},
                        ninth: {},
                        tenth: {},
                        eleventh: {},
                        twelfth: {},
                        thirteenth: {},
                        fourteenth: {},
                        fifteenth: {},
                        sixteenth: {},
                        seventeenth: {},
                        eighteenth: {},
                        nineteenth: {},
                        twentieth: {},
                        twentyFirst: {},
                        twentySecond: {},
                        twentyThird: {},
                        twentyFourth: {},
                        twentyFifth: {},
                        twentySixth: {},
                        twentySeventh: {},
                        twentyEighth: {},
                        twentyNinth: {},
                        thirtieth: {},
                        thirtyFirst: {},
                    },
                    june: {
                        first: {},
                        second: {},
                        third: {},
                        fourth: {},
                        fifth: {},
                        sixth: {},
                        seventh: {},
                        eighth: {},
                        ninth: {},
                        tenth: {},
                        eleventh: {},
                        twelfth: {},
                        thirteenth: {},
                        fourteenth: {},
                        fifteenth: {},
                        sixteenth: {},
                        seventeenth: {},
                        eighteenth: {},
                        nineteenth: {},
                        twentieth: {},
                        twentyFirst: {},
                        twentySecond: {},
                        twentyThird: {},
                        twentyFourth: {},
                        twentyFifth: {},
                        twentySixth: {},
                        twentySeventh: {},
                        twentyEighth: {},
                        twentyNinth: {},
                        thirtieth: {},
                    },
                },
                summer: {
                    july: {
                        first: {},
                        second: {},
                        third: {},
                        fourth: {},
                        fifth: {},
                        sixth: {},
                        seventh: {},
                        eighth: {},
                        ninth: {},
                        tenth: {},
                        eleventh: {},
                        twelfth: {},
                        thirteenth: {},
                        fourteenth: {},
                        fifteenth: {},
                        sixteenth: {},
                        seventeenth: {},
                        eighteenth: {},
                        nineteenth: {},
                        twentieth: {},
                        twentyFirst: {},
                        twentySecond: {},
                        twentyThird: {},
                        twentyFourth: {},
                        twentyFifth: {},
                        twentySixth: {},
                        twentySeventh: {},
                        twentyEighth: {},
                        twentyNinth: {},
                        thirtieth: {},
                        thirtyFirst: {},
                    },
                    august: {
                        first: {},
                        second: {},
                        third: {},
                        fourth: {},
                        fifth: {},
                        sixth: {},
                        seventh: {},
                        eighth: {},
                        ninth: {},
                        tenth: {},
                        eleventh: {},
                        twelfth: {},
                        thirteenth: {},
                        fourteenth: {},
                        fifteenth: {},
                        sixteenth: {},
                        seventeenth: {},
                        eighteenth: {},
                        nineteenth: {},
                        twentieth: {},
                        twentyFirst: {},
                        twentySecond: {},
                        twentyThird: {},
                        twentyFourth: {},
                        twentyFifth: {},
                        twentySixth: {},
                        twentySeventh: {},
                        twentyEighth: {},
                        twentyNinth: {},
                        thirtieth: {},
                        thirtyFirst: {},
                    },
                    september: {
                        first: {},
                        second: {},
                        third: {},
                        fourth: {},
                        fifth: {},
                        sixth: {},
                        seventh: {},
                        eighth: {},
                        ninth: {},
                        tenth: {},
                        eleventh: {},
                        twelfth: {},
                        thirteenth: {},
                        fourteenth: {},
                        fifteenth: {},
                        sixteenth: {},
                        seventeenth: {},
                        eighteenth: {},
                        nineteenth: {},
                        twentieth: {},
                        twentyFirst: {},
                        twentySecond: {},
                        twentyThird: {},
                        twentyFourth: {},
                        twentyFifth: {},
                        twentySixth: {},
                        twentySeventh: {},
                        twentyEighth: {},
                        twentyNinth: {},
                        thirtieth: {},
                    },
                },
                autumn: {
                    october: {
                        first: {},
                        second: {},
                        third: {},
                        fourth: {},
                        fifth: {},
                        sixth: {},
                        seventh: {},
                        eighth: {},
                        ninth: {},
                        tenth: {},
                        eleventh: {},
                        twelfth: {},
                        thirteenth: {},
                        fourteenth: {},
                        fifteenth: {},
                        sixteenth: {},
                        seventeenth: {},
                        eighteenth: {},
                        nineteenth: {},
                        twentieth: {},
                        twentyFirst: {},
                        twentySecond: {},
                        twentyThird: {},
                        twentyFourth: {},
                        twentyFifth: {},
                        twentySixth: {},
                        twentySeventh: {},
                        twentyEighth: {},
                        twentyNinth: {},
                        thirtieth: {},
                        thirtyFirst: {},
                    },
                    november: {
                        first: {},
                        second: {},
                        third: {},
                        fourth: {},
                        fifth: {},
                        sixth: {},
                        seventh: {},
                        eighth: {},
                        ninth: {},
                        tenth: {},
                        eleventh: {},
                        twelfth: {},
                        thirteenth: {},
                        fourteenth: {},
                        fifteenth: {},
                        sixteenth: {},
                        seventeenth: {},
                        eighteenth: {},
                        nineteenth: {},
                        twentieth: {},
                        twentyFirst: {},
                        twentySecond: {},
                        twentyThird: {},
                        twentyFourth: {},
                        twentyFifth: {},
                        twentySixth: {},
                        twentySeventh: {},
                        twentyEighth: {},
                        twentyNinth: {},
                        thirtieth: {},
                    },
                    december: {
                        first: {},
                        second: {},
                        third: {},
                        fourth: {},
                        fifth: {},
                        sixth: {},
                        seventh: {},
                        eighth: {},
                        ninth: {},
                        tenth: {},
                        eleventh: {},
                        twelfth: {},
                        thirteenth: {},
                        fourteenth: {},
                        fifteenth: {},
                        sixteenth: {},
                        seventeenth: {},
                        eighteenth: {},
                        nineteenth: {},
                        twentieth: {},
                        twentyFirst: {},
                        twentySecond: {},
                        twentyThird: {},
                        twentyFourth: {},
                        twentyFifth: {},
                        twentySixth: {},
                        twentySeventh: {},
                        twentyEighth: {},
                        twentyNinth: {},
                        thirtieth: {},
                        thirtyFirst: {},
                    },
                },
            },
        }

    };

    return Availability;
};

const createYearlyHotelAvailability = (year) => {
    if (year % 4 === 0) {
        console.log("skip year");
        let Availability = skipYearTemplate(year);

        return Availability;
    } else {
        console.log("regular year");
        let Availability = regularYearTemplate(year);
        
        return Availability;
    };
};



module.exports = {
    createYearlyHotelAvailability,
};