const getRoomsAvailability = () => {
    let totalRooms = {
        closeForSale: false,

        standardRooms: {
            id: "001",
            name: "Standard Room",
            categoryCloseForSale: false,

            totalAmountRooms: 50,
            availableRooms: 50,

            prices: {
                priceRates: {
                    single: 0.9,
                    double: 1,
                    triple: 1.25,
                    tripleAdults: 1.3,
                    quad: 1.5,
                },
                baby: 40,
            },

            capacity: {
                maxCapacity: [
                    { adults: 3, kids: 0, babies: 0 },
                    { adults: 2, kids: 2, babies: 0 },
                    { adults: 2, kids: 1, babies: 1 },
                    { adults: 2, kids: 0, babies: 2 },
                ],
                minCapacity: [
                    { adults: 1, kids: 0, babies: 0 },
                    { adults: 0, kids: 1, babies: 0 },
                ],
                ProhibitedCapacity: [
                    { adults: 0, kids: 0, babies: 1 },
                ],
            },
        },

        executiveRooms: {
            id: "002",
            name: "Executive Room",
            categoryCloseForSale: false,
    
            totalAmountRooms: 40,
            availableRooms: 40,
            
            prices: {
                priceRates: {
                    single: 1.2,
                    double: 1.3,
                    triple: 1.7,
                    tripleAdults: 1.8,
                },
                babies: 40,
            },
            capacity: {
                maxCapacity: [
                    { adults: 3, kids: 0, babies: 0 },
                    { adults: 2, kids: 1, babies: 0 },
                    { adults: 2, kids: 0, babies: 1 },
                ],
                minCapacity: [
                    { adults: 1, kids: 0, babies: 0 },
                    { adults: 0, kids: 1, babies: 0 },
                ],
                ProhibitedCapacity: [
                    { adults: 0, kids: 0, babies: 1 },
                ],
            },
        },

        suiteRooms: {
            id: "003",
            name: "Suite",
            categoryCloseForSale: false,
    
            totalAmountRooms: 10,
            availableRooms: 10,
            
            prices: {
                priceRates: {
                    single: 5,
                    double: 5.1,
                },
                babies: 40,
            },
            capacity: {
                maxCapacity: [
                    { adults: 2, kids: 0, babies: 1 },
                    { adults: 2, kids: 0, babies: 0 },
                ],
                minCapacity: [
                    { adults: 1, kids: 0, babies: 0 },
                ],
                ProhibitedCapacity: [
                    { adults: 0, kids: 1, babies: 0 },
                    { adults: 0, kids: 0, babies: 1 },
                ],
            },
        },
    };

    return totalRooms;
};


const dayTemplate = () => {
    let day = {
        day: "",
        // numericalDay: 0,
        comment: "",
        note: "",

        priceStage: 5,

        roomsAvailable: getRoomsAvailability(),
        
    };

    return day;
};

const regularYearTemplate = (year) => {
    let Availability = {
            year: year,

            seasons: {
                winter: {
                    january: {
                        first: dayTemplate(),
                        second: dayTemplate(),
                        third: dayTemplate(),
                        fourth: dayTemplate(),
                        fifth: dayTemplate(),
                        sixth: dayTemplate(),
                        seventh: dayTemplate(),
                        eighth: dayTemplate(),
                        ninth: dayTemplate(),
                        tenth: dayTemplate(),
                        eleventh: dayTemplate(),
                        twelfth: dayTemplate(),
                        thirteenth: dayTemplate(),
                        fourteenth: dayTemplate(),
                        fifteenth: dayTemplate(),
                        sixteenth: dayTemplate(),
                        seventeenth: dayTemplate(),
                        eighteenth: dayTemplate(),
                        nineteenth: dayTemplate(),
                        twentieth: dayTemplate(),
                        twentyFirst: dayTemplate(),
                        twentySecond: dayTemplate(),
                        twentyThird: dayTemplate(),
                        twentyFourth: dayTemplate(),
                        twentyFifth: dayTemplate(),
                        twentySixth: dayTemplate(),
                        twentySeventh: dayTemplate(),
                        twentyEighth: dayTemplate(),
                        twentyNinth: dayTemplate(),
                        thirtieth: dayTemplate(),
                        thirtyFirst: dayTemplate(),
                    },
                    february: {
                        first: dayTemplate(),
                        second: dayTemplate(),
                        third: dayTemplate(),
                        fourth: dayTemplate(),
                        fifth: dayTemplate(),
                        sixth: dayTemplate(),
                        seventh: dayTemplate(),
                        eighth: dayTemplate(),
                        ninth: dayTemplate(),
                        tenth: dayTemplate(),
                        eleventh: dayTemplate(),
                        twelfth: dayTemplate(),
                        thirteenth: dayTemplate(),
                        fourteenth: dayTemplate(),
                        fifteenth: dayTemplate(),
                        sixteenth: dayTemplate(),
                        seventeenth: dayTemplate(),
                        eighteenth: dayTemplate(),
                        nineteenth: dayTemplate(),
                        twentieth: dayTemplate(),
                        twentyFirst: dayTemplate(),
                        twentySecond: dayTemplate(),
                        twentyThird: dayTemplate(),
                        twentyFourth: dayTemplate(),
                        twentyFifth: dayTemplate(),
                        twentySixth: dayTemplate(),
                        twentySeventh: dayTemplate(),
                        twentyEighth: dayTemplate(),
                    },
                    march: {
                        first: dayTemplate(),
                        second: dayTemplate(),
                        third: dayTemplate(),
                        fourth: dayTemplate(),
                        fifth: dayTemplate(),
                        sixth: dayTemplate(),
                        seventh: dayTemplate(),
                        eighth: dayTemplate(),
                        ninth: dayTemplate(),
                        tenth: dayTemplate(),
                        eleventh: dayTemplate(),
                        twelfth: dayTemplate(),
                        thirteenth: dayTemplate(),
                        fourteenth: dayTemplate(),
                        fifteenth: dayTemplate(),
                        sixteenth: dayTemplate(),
                        seventeenth: dayTemplate(),
                        eighteenth: dayTemplate(),
                        nineteenth: dayTemplate(),
                        twentieth: dayTemplate(),
                        twentyFirst: dayTemplate(),
                        twentySecond: dayTemplate(),
                        twentyThird: dayTemplate(),
                        twentyFourth: dayTemplate(),
                        twentyFifth: dayTemplate(),
                        twentySixth: dayTemplate(),
                        twentySeventh: dayTemplate(),
                        twentyEighth: dayTemplate(),
                        twentyNinth: dayTemplate(),
                        thirtieth: dayTemplate(),
                        thirtyFirst: dayTemplate(),
                    },
                },
                spring: {
                    april: {
                        first: dayTemplate(),
                        second: dayTemplate(),
                        third: dayTemplate(),
                        fourth: dayTemplate(),
                        fifth: dayTemplate(),
                        sixth: dayTemplate(),
                        seventh: dayTemplate(),
                        eighth: dayTemplate(),
                        ninth: dayTemplate(),
                        tenth: dayTemplate(),
                        eleventh: dayTemplate(),
                        twelfth: dayTemplate(),
                        thirteenth: dayTemplate(),
                        fourteenth: dayTemplate(),
                        fifteenth: dayTemplate(),
                        sixteenth: dayTemplate(),
                        seventeenth: dayTemplate(),
                        eighteenth: dayTemplate(),
                        nineteenth: dayTemplate(),
                        twentieth: dayTemplate(),
                        twentyFirst: dayTemplate(),
                        twentySecond: dayTemplate(),
                        twentyThird: dayTemplate(),
                        twentyFourth: dayTemplate(),
                        twentyFifth: dayTemplate(),
                        twentySixth: dayTemplate(),
                        twentySeventh: dayTemplate(),
                        twentyEighth: dayTemplate(),
                        twentyNinth: dayTemplate(),
                        thirtieth: dayTemplate(),
                    },
                    may: {
                        first: dayTemplate(),
                        second: dayTemplate(),
                        third: dayTemplate(),
                        fourth: dayTemplate(),
                        fifth: dayTemplate(),
                        sixth: dayTemplate(),
                        seventh: dayTemplate(),
                        eighth: dayTemplate(),
                        ninth: dayTemplate(),
                        tenth: dayTemplate(),
                        eleventh: dayTemplate(),
                        twelfth: dayTemplate(),
                        thirteenth: dayTemplate(),
                        fourteenth: dayTemplate(),
                        fifteenth: dayTemplate(),
                        sixteenth: dayTemplate(),
                        seventeenth: dayTemplate(),
                        eighteenth: dayTemplate(),
                        nineteenth: dayTemplate(),
                        twentieth: dayTemplate(),
                        twentyFirst: dayTemplate(),
                        twentySecond: dayTemplate(),
                        twentyThird: dayTemplate(),
                        twentyFourth: dayTemplate(),
                        twentyFifth: dayTemplate(),
                        twentySixth: dayTemplate(),
                        twentySeventh: dayTemplate(),
                        twentyEighth: dayTemplate(),
                        twentyNinth: dayTemplate(),
                        thirtieth: dayTemplate(),
                        thirtyFirst: dayTemplate(),
                    },
                    june: {
                        first: dayTemplate(),
                        second: dayTemplate(),
                        third: dayTemplate(),
                        fourth: dayTemplate(),
                        fifth: dayTemplate(),
                        sixth: dayTemplate(),
                        seventh: dayTemplate(),
                        eighth: dayTemplate(),
                        ninth: dayTemplate(),
                        tenth: dayTemplate(),
                        eleventh: dayTemplate(),
                        twelfth: dayTemplate(),
                        thirteenth: dayTemplate(),
                        fourteenth: dayTemplate(),
                        fifteenth: dayTemplate(),
                        sixteenth: dayTemplate(),
                        seventeenth: dayTemplate(),
                        eighteenth: dayTemplate(),
                        nineteenth: dayTemplate(),
                        twentieth: dayTemplate(),
                        twentyFirst: dayTemplate(),
                        twentySecond: dayTemplate(),
                        twentyThird: dayTemplate(),
                        twentyFourth: dayTemplate(),
                        twentyFifth: dayTemplate(),
                        twentySixth: dayTemplate(),
                        twentySeventh: dayTemplate(),
                        twentyEighth: dayTemplate(),
                        twentyNinth: dayTemplate(),
                        thirtieth: dayTemplate(),
                    },
                },
                summer: {
                    july: {
                        first: dayTemplate(),
                        second: dayTemplate(),
                        third: dayTemplate(),
                        fourth: dayTemplate(),
                        fifth: dayTemplate(),
                        sixth: dayTemplate(),
                        seventh: dayTemplate(),
                        eighth: dayTemplate(),
                        ninth: dayTemplate(),
                        tenth: dayTemplate(),
                        eleventh: dayTemplate(),
                        twelfth: dayTemplate(),
                        thirteenth: dayTemplate(),
                        fourteenth: dayTemplate(),
                        fifteenth: dayTemplate(),
                        sixteenth: dayTemplate(),
                        seventeenth: dayTemplate(),
                        eighteenth: dayTemplate(),
                        nineteenth: dayTemplate(),
                        twentieth: dayTemplate(),
                        twentyFirst: dayTemplate(),
                        twentySecond: dayTemplate(),
                        twentyThird: dayTemplate(),
                        twentyFourth: dayTemplate(),
                        twentyFifth: dayTemplate(),
                        twentySixth: dayTemplate(),
                        twentySeventh: dayTemplate(),
                        twentyEighth: dayTemplate(),
                        twentyNinth: dayTemplate(),
                        thirtieth: dayTemplate(),
                        thirtyFirst: dayTemplate(),
                    },
                    august: {
                        first: dayTemplate(),
                        second: dayTemplate(),
                        third: dayTemplate(),
                        fourth: dayTemplate(),
                        fifth: dayTemplate(),
                        sixth: dayTemplate(),
                        seventh: dayTemplate(),
                        eighth: dayTemplate(),
                        ninth: dayTemplate(),
                        tenth: dayTemplate(),
                        eleventh: dayTemplate(),
                        twelfth: dayTemplate(),
                        thirteenth: dayTemplate(),
                        fourteenth: dayTemplate(),
                        fifteenth: dayTemplate(),
                        sixteenth: dayTemplate(),
                        seventeenth: dayTemplate(),
                        eighteenth: dayTemplate(),
                        nineteenth: dayTemplate(),
                        twentieth: dayTemplate(),
                        twentyFirst: dayTemplate(),
                        twentySecond: dayTemplate(),
                        twentyThird: dayTemplate(),
                        twentyFourth: dayTemplate(),
                        twentyFifth: dayTemplate(),
                        twentySixth: dayTemplate(),
                        twentySeventh: dayTemplate(),
                        twentyEighth: dayTemplate(),
                        twentyNinth: dayTemplate(),
                        thirtieth: dayTemplate(),
                        thirtyFirst: dayTemplate(),
                    },
                    september: {
                        first: dayTemplate(),
                        second: dayTemplate(),
                        third: dayTemplate(),
                        fourth: dayTemplate(),
                        fifth: dayTemplate(),
                        sixth: dayTemplate(),
                        seventh: dayTemplate(),
                        eighth: dayTemplate(),
                        ninth: dayTemplate(),
                        tenth: dayTemplate(),
                        eleventh: dayTemplate(),
                        twelfth: dayTemplate(),
                        thirteenth: dayTemplate(),
                        fourteenth: dayTemplate(),
                        fifteenth: dayTemplate(),
                        sixteenth: dayTemplate(),
                        seventeenth: dayTemplate(),
                        eighteenth: dayTemplate(),
                        nineteenth: dayTemplate(),
                        twentieth: dayTemplate(),
                        twentyFirst: dayTemplate(),
                        twentySecond: dayTemplate(),
                        twentyThird: dayTemplate(),
                        twentyFourth: dayTemplate(),
                        twentyFifth: dayTemplate(),
                        twentySixth: dayTemplate(),
                        twentySeventh: dayTemplate(),
                        twentyEighth: dayTemplate(),
                        twentyNinth: dayTemplate(),
                        thirtieth: dayTemplate(),
                    },
                },
                autumn: {
                    october: {
                        first: dayTemplate(),
                        second: dayTemplate(),
                        third: dayTemplate(),
                        fourth: dayTemplate(),
                        fifth: dayTemplate(),
                        sixth: dayTemplate(),
                        seventh: dayTemplate(),
                        eighth: dayTemplate(),
                        ninth: dayTemplate(),
                        tenth: dayTemplate(),
                        eleventh: dayTemplate(),
                        twelfth: dayTemplate(),
                        thirteenth: dayTemplate(),
                        fourteenth: dayTemplate(),
                        fifteenth: dayTemplate(),
                        sixteenth: dayTemplate(),
                        seventeenth: dayTemplate(),
                        eighteenth: dayTemplate(),
                        nineteenth: dayTemplate(),
                        twentieth: dayTemplate(),
                        twentyFirst: dayTemplate(),
                        twentySecond: dayTemplate(),
                        twentyThird: dayTemplate(),
                        twentyFourth: dayTemplate(),
                        twentyFifth: dayTemplate(),
                        twentySixth: dayTemplate(),
                        twentySeventh: dayTemplate(),
                        twentyEighth: dayTemplate(),
                        twentyNinth: dayTemplate(),
                        thirtieth: dayTemplate(),
                        thirtyFirst: dayTemplate(),
                    },
                    november: {
                        first: dayTemplate(),
                        second: dayTemplate(),
                        third: dayTemplate(),
                        fourth: dayTemplate(),
                        fifth: dayTemplate(),
                        sixth: dayTemplate(),
                        seventh: dayTemplate(),
                        eighth: dayTemplate(),
                        ninth: dayTemplate(),
                        tenth: dayTemplate(),
                        eleventh: dayTemplate(),
                        twelfth: dayTemplate(),
                        thirteenth: dayTemplate(),
                        fourteenth: dayTemplate(),
                        fifteenth: dayTemplate(),
                        sixteenth: dayTemplate(),
                        seventeenth: dayTemplate(),
                        eighteenth: dayTemplate(),
                        nineteenth: dayTemplate(),
                        twentieth: dayTemplate(),
                        twentyFirst: dayTemplate(),
                        twentySecond: dayTemplate(),
                        twentyThird: dayTemplate(),
                        twentyFourth: dayTemplate(),
                        twentyFifth: dayTemplate(),
                        twentySixth: dayTemplate(),
                        twentySeventh: dayTemplate(),
                        twentyEighth: dayTemplate(),
                        twentyNinth: dayTemplate(),
                        thirtieth: dayTemplate(),
                    },
                    december: {
                        first: dayTemplate(),
                        second: dayTemplate(),
                        third: dayTemplate(),
                        fourth: dayTemplate(),
                        fifth: dayTemplate(),
                        sixth: dayTemplate(),
                        seventh: dayTemplate(),
                        eighth: dayTemplate(),
                        ninth: dayTemplate(),
                        tenth: dayTemplate(),
                        eleventh: dayTemplate(),
                        twelfth: dayTemplate(),
                        thirteenth: dayTemplate(),
                        fourteenth: dayTemplate(),
                        fifteenth: dayTemplate(),
                        sixteenth: dayTemplate(),
                        seventeenth: dayTemplate(),
                        eighteenth: dayTemplate(),
                        nineteenth: dayTemplate(),
                        twentieth: dayTemplate(),
                        twentyFirst: dayTemplate(),
                        twentySecond: dayTemplate(),
                        twentyThird: dayTemplate(),
                        twentyFourth: dayTemplate(),
                        twentyFifth: dayTemplate(),
                        twentySixth: dayTemplate(),
                        twentySeventh: dayTemplate(),
                        twentyEighth: dayTemplate(),
                        twentyNinth: dayTemplate(),
                        thirtieth: dayTemplate(),
                        thirtyFirst: dayTemplate(),
                    },
                },
            },
    };

    return Availability;
};


const skipYearTemplate = (year) => {
    let Availability = {
        year: year,

        seasons: {
            winter: {
                january: {
                    first: dayTemplate(),
                    second: dayTemplate(),
                    third: dayTemplate(),
                    fourth: dayTemplate(),
                    fifth: dayTemplate(),
                    sixth: dayTemplate(),
                    seventh: dayTemplate(),
                    eighth: dayTemplate(),
                    ninth: dayTemplate(),
                    tenth: dayTemplate(),
                    eleventh: dayTemplate(),
                    twelfth: dayTemplate(),
                    thirteenth: dayTemplate(),
                    fourteenth: dayTemplate(),
                    fifteenth: dayTemplate(),
                    sixteenth: dayTemplate(),
                    seventeenth: dayTemplate(),
                    eighteenth: dayTemplate(),
                    nineteenth: dayTemplate(),
                    twentieth: dayTemplate(),
                    twentyFirst: dayTemplate(),
                    twentySecond: dayTemplate(),
                    twentyThird: dayTemplate(),
                    twentyFourth: dayTemplate(),
                    twentyFifth: dayTemplate(),
                    twentySixth: dayTemplate(),
                    twentySeventh: dayTemplate(),
                    twentyEighth: dayTemplate(),
                    twentyNinth: dayTemplate(),
                    thirtieth: dayTemplate(),
                    thirtyFirst: dayTemplate(),
                },
                february: {
                    first: dayTemplate(),
                    second: dayTemplate(),
                    third: dayTemplate(),
                    fourth: dayTemplate(),
                    fifth: dayTemplate(),
                    sixth: dayTemplate(),
                    seventh: dayTemplate(),
                    eighth: dayTemplate(),
                    ninth: dayTemplate(),
                    tenth: dayTemplate(),
                    eleventh: dayTemplate(),
                    twelfth: dayTemplate(),
                    thirteenth: dayTemplate(),
                    fourteenth: dayTemplate(),
                    fifteenth: dayTemplate(),
                    sixteenth: dayTemplate(),
                    seventeenth: dayTemplate(),
                    eighteenth: dayTemplate(),
                    nineteenth: dayTemplate(),
                    twentieth: dayTemplate(),
                    twentyFirst: dayTemplate(),
                    twentySecond: dayTemplate(),
                    twentyThird: dayTemplate(),
                    twentyFourth: dayTemplate(),
                    twentyFifth: dayTemplate(),
                    twentySixth: dayTemplate(),
                    twentySeventh: dayTemplate(),
                    twentyEighth: dayTemplate(),
                    twentyNinth: dayTemplate(),
                },
                march: {
                    first: dayTemplate(),
                    second: dayTemplate(),
                    third: dayTemplate(),
                    fourth: dayTemplate(),
                    fifth: dayTemplate(),
                    sixth: dayTemplate(),
                    seventh: dayTemplate(),
                    eighth: dayTemplate(),
                    ninth: dayTemplate(),
                    tenth: dayTemplate(),
                    eleventh: dayTemplate(),
                    twelfth: dayTemplate(),
                    thirteenth: dayTemplate(),
                    fourteenth: dayTemplate(),
                    fifteenth: dayTemplate(),
                    sixteenth: dayTemplate(),
                    seventeenth: dayTemplate(),
                    eighteenth: dayTemplate(),
                    nineteenth: dayTemplate(),
                    twentieth: dayTemplate(),
                    twentyFirst: dayTemplate(),
                    twentySecond: dayTemplate(),
                    twentyThird: dayTemplate(),
                    twentyFourth: dayTemplate(),
                    twentyFifth: dayTemplate(),
                    twentySixth: dayTemplate(),
                    twentySeventh: dayTemplate(),
                    twentyEighth: dayTemplate(),
                    twentyNinth: dayTemplate(),
                    thirtieth: dayTemplate(),
                    thirtyFirst: dayTemplate(),
                },
            },
            spring: {
                april: {
                    first: dayTemplate(),
                    second: dayTemplate(),
                    third: dayTemplate(),
                    fourth: dayTemplate(),
                    fifth: dayTemplate(),
                    sixth: dayTemplate(),
                    seventh: dayTemplate(),
                    eighth: dayTemplate(),
                    ninth: dayTemplate(),
                    tenth: dayTemplate(),
                    eleventh: dayTemplate(),
                    twelfth: dayTemplate(),
                    thirteenth: dayTemplate(),
                    fourteenth: dayTemplate(),
                    fifteenth: dayTemplate(),
                    sixteenth: dayTemplate(),
                    seventeenth: dayTemplate(),
                    eighteenth: dayTemplate(),
                    nineteenth: dayTemplate(),
                    twentieth: dayTemplate(),
                    twentyFirst: dayTemplate(),
                    twentySecond: dayTemplate(),
                    twentyThird: dayTemplate(),
                    twentyFourth: dayTemplate(),
                    twentyFifth: dayTemplate(),
                    twentySixth: dayTemplate(),
                    twentySeventh: dayTemplate(),
                    twentyEighth: dayTemplate(),
                    twentyNinth: dayTemplate(),
                    thirtieth: dayTemplate(),
                },
                may: {
                    first: dayTemplate(),
                    second: dayTemplate(),
                    third: dayTemplate(),
                    fourth: dayTemplate(),
                    fifth: dayTemplate(),
                    sixth: dayTemplate(),
                    seventh: dayTemplate(),
                    eighth: dayTemplate(),
                    ninth: dayTemplate(),
                    tenth: dayTemplate(),
                    eleventh: dayTemplate(),
                    twelfth: dayTemplate(),
                    thirteenth: dayTemplate(),
                    fourteenth: dayTemplate(),
                    fifteenth: dayTemplate(),
                    sixteenth: dayTemplate(),
                    seventeenth: dayTemplate(),
                    eighteenth: dayTemplate(),
                    nineteenth: dayTemplate(),
                    twentieth: dayTemplate(),
                    twentyFirst: dayTemplate(),
                    twentySecond: dayTemplate(),
                    twentyThird: dayTemplate(),
                    twentyFourth: dayTemplate(),
                    twentyFifth: dayTemplate(),
                    twentySixth: dayTemplate(),
                    twentySeventh: dayTemplate(),
                    twentyEighth: dayTemplate(),
                    twentyNinth: dayTemplate(),
                    thirtieth: dayTemplate(),
                    thirtyFirst: dayTemplate(),
                },
                june: {
                    first: dayTemplate(),
                    second: dayTemplate(),
                    third: dayTemplate(),
                    fourth: dayTemplate(),
                    fifth: dayTemplate(),
                    sixth: dayTemplate(),
                    seventh: dayTemplate(),
                    eighth: dayTemplate(),
                    ninth: dayTemplate(),
                    tenth: dayTemplate(),
                    eleventh: dayTemplate(),
                    twelfth: dayTemplate(),
                    thirteenth: dayTemplate(),
                    fourteenth: dayTemplate(),
                    fifteenth: dayTemplate(),
                    sixteenth: dayTemplate(),
                    seventeenth: dayTemplate(),
                    eighteenth: dayTemplate(),
                    nineteenth: dayTemplate(),
                    twentieth: dayTemplate(),
                    twentyFirst: dayTemplate(),
                    twentySecond: dayTemplate(),
                    twentyThird: dayTemplate(),
                    twentyFourth: dayTemplate(),
                    twentyFifth: dayTemplate(),
                    twentySixth: dayTemplate(),
                    twentySeventh: dayTemplate(),
                    twentyEighth: dayTemplate(),
                    twentyNinth: dayTemplate(),
                    thirtieth: dayTemplate(),
                },
            },
            summer: {
                july: {
                    first: dayTemplate(),
                    second: dayTemplate(),
                    third: dayTemplate(),
                    fourth: dayTemplate(),
                    fifth: dayTemplate(),
                    sixth: dayTemplate(),
                    seventh: dayTemplate(),
                    eighth: dayTemplate(),
                    ninth: dayTemplate(),
                    tenth: dayTemplate(),
                    eleventh: dayTemplate(),
                    twelfth: dayTemplate(),
                    thirteenth: dayTemplate(),
                    fourteenth: dayTemplate(),
                    fifteenth: dayTemplate(),
                    sixteenth: dayTemplate(),
                    seventeenth: dayTemplate(),
                    eighteenth: dayTemplate(),
                    nineteenth: dayTemplate(),
                    twentieth: dayTemplate(),
                    twentyFirst: dayTemplate(),
                    twentySecond: dayTemplate(),
                    twentyThird: dayTemplate(),
                    twentyFourth: dayTemplate(),
                    twentyFifth: dayTemplate(),
                    twentySixth: dayTemplate(),
                    twentySeventh: dayTemplate(),
                    twentyEighth: dayTemplate(),
                    twentyNinth: dayTemplate(),
                    thirtieth: dayTemplate(),
                    thirtyFirst: dayTemplate(),
                },
                august: {
                    first: dayTemplate(),
                    second: dayTemplate(),
                    third: dayTemplate(),
                    fourth: dayTemplate(),
                    fifth: dayTemplate(),
                    sixth: dayTemplate(),
                    seventh: dayTemplate(),
                    eighth: dayTemplate(),
                    ninth: dayTemplate(),
                    tenth: dayTemplate(),
                    eleventh: dayTemplate(),
                    twelfth: dayTemplate(),
                    thirteenth: dayTemplate(),
                    fourteenth: dayTemplate(),
                    fifteenth: dayTemplate(),
                    sixteenth: dayTemplate(),
                    seventeenth: dayTemplate(),
                    eighteenth: dayTemplate(),
                    nineteenth: dayTemplate(),
                    twentieth: dayTemplate(),
                    twentyFirst: dayTemplate(),
                    twentySecond: dayTemplate(),
                    twentyThird: dayTemplate(),
                    twentyFourth: dayTemplate(),
                    twentyFifth: dayTemplate(),
                    twentySixth: dayTemplate(),
                    twentySeventh: dayTemplate(),
                    twentyEighth: dayTemplate(),
                    twentyNinth: dayTemplate(),
                    thirtieth: dayTemplate(),
                    thirtyFirst: dayTemplate(),
                },
                september: {
                    first: dayTemplate(),
                    second: dayTemplate(),
                    third: dayTemplate(),
                    fourth: dayTemplate(),
                    fifth: dayTemplate(),
                    sixth: dayTemplate(),
                    seventh: dayTemplate(),
                    eighth: dayTemplate(),
                    ninth: dayTemplate(),
                    tenth: dayTemplate(),
                    eleventh: dayTemplate(),
                    twelfth: dayTemplate(),
                    thirteenth: dayTemplate(),
                    fourteenth: dayTemplate(),
                    fifteenth: dayTemplate(),
                    sixteenth: dayTemplate(),
                    seventeenth: dayTemplate(),
                    eighteenth: dayTemplate(),
                    nineteenth: dayTemplate(),
                    twentieth: dayTemplate(),
                    twentyFirst: dayTemplate(),
                    twentySecond: dayTemplate(),
                    twentyThird: dayTemplate(),
                    twentyFourth: dayTemplate(),
                    twentyFifth: dayTemplate(),
                    twentySixth: dayTemplate(),
                    twentySeventh: dayTemplate(),
                    twentyEighth: dayTemplate(),
                    twentyNinth: dayTemplate(),
                    thirtieth: dayTemplate(),
                },
            },
            autumn: {
                october: {
                    first: dayTemplate(),
                    second: dayTemplate(),
                    third: dayTemplate(),
                    fourth: dayTemplate(),
                    fifth: dayTemplate(),
                    sixth: dayTemplate(),
                    seventh: dayTemplate(),
                    eighth: dayTemplate(),
                    ninth: dayTemplate(),
                    tenth: dayTemplate(),
                    eleventh: dayTemplate(),
                    twelfth: dayTemplate(),
                    thirteenth: dayTemplate(),
                    fourteenth: dayTemplate(),
                    fifteenth: dayTemplate(),
                    sixteenth: dayTemplate(),
                    seventeenth: dayTemplate(),
                    eighteenth: dayTemplate(),
                    nineteenth: dayTemplate(),
                    twentieth: dayTemplate(),
                    twentyFirst: dayTemplate(),
                    twentySecond: dayTemplate(),
                    twentyThird: dayTemplate(),
                    twentyFourth: dayTemplate(),
                    twentyFifth: dayTemplate(),
                    twentySixth: dayTemplate(),
                    twentySeventh: dayTemplate(),
                    twentyEighth: dayTemplate(),
                    twentyNinth: dayTemplate(),
                    thirtieth: dayTemplate(),
                    thirtyFirst: dayTemplate(),
                },
                november: {
                    first: dayTemplate(),
                    second: dayTemplate(),
                    third: dayTemplate(),
                    fourth: dayTemplate(),
                    fifth: dayTemplate(),
                    sixth: dayTemplate(),
                    seventh: dayTemplate(),
                    eighth: dayTemplate(),
                    ninth: dayTemplate(),
                    tenth: dayTemplate(),
                    eleventh: dayTemplate(),
                    twelfth: dayTemplate(),
                    thirteenth: dayTemplate(),
                    fourteenth: dayTemplate(),
                    fifteenth: dayTemplate(),
                    sixteenth: dayTemplate(),
                    seventeenth: dayTemplate(),
                    eighteenth: dayTemplate(),
                    nineteenth: dayTemplate(),
                    twentieth: dayTemplate(),
                    twentyFirst: dayTemplate(),
                    twentySecond: dayTemplate(),
                    twentyThird: dayTemplate(),
                    twentyFourth: dayTemplate(),
                    twentyFifth: dayTemplate(),
                    twentySixth: dayTemplate(),
                    twentySeventh: dayTemplate(),
                    twentyEighth: dayTemplate(),
                    twentyNinth: dayTemplate(),
                    thirtieth: dayTemplate(),
                },
                december: {
                    first: dayTemplate(),
                    second: dayTemplate(),
                    third: dayTemplate(),
                    fourth: dayTemplate(),
                    fifth: dayTemplate(),
                    sixth: dayTemplate(),
                    seventh: dayTemplate(),
                    eighth: dayTemplate(),
                    ninth: dayTemplate(),
                    tenth: dayTemplate(),
                    eleventh: dayTemplate(),
                    twelfth: dayTemplate(),
                    thirteenth: dayTemplate(),
                    fourteenth: dayTemplate(),
                    fifteenth: dayTemplate(),
                    sixteenth: dayTemplate(),
                    seventeenth: dayTemplate(),
                    eighteenth: dayTemplate(),
                    nineteenth: dayTemplate(),
                    twentieth: dayTemplate(),
                    twentyFirst: dayTemplate(),
                    twentySecond: dayTemplate(),
                    twentyThird: dayTemplate(),
                    twentyFourth: dayTemplate(),
                    twentyFifth: dayTemplate(),
                    twentySixth: dayTemplate(),
                    twentySeventh: dayTemplate(),
                    twentyEighth: dayTemplate(),
                    twentyNinth: dayTemplate(),
                    thirtieth: dayTemplate(),
                    thirtyFirst: dayTemplate(),
                },
            },
        },
    };

    return Availability;
};

const createYearlyHotelAvailability = (year) => {
    if (year % 4 === 0) {
        let Availability = skipYearTemplate(year);

        return Availability;
    } else {
        let Availability = regularYearTemplate(year);
        
        return Availability;
    };
};



module.exports = {
    createYearlyHotelAvailability,
};